---
include:
  - "**/*.rb"
  - "Rakefile"
  - "Gemfile"
  - "*.gemspec"
  - "config/**/*.rb"
  - "app/**/*.rb"
  - "lib/**/*.rb"
  - "db/**/*.rb"
exclude:
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"
  - ".bundle/**/*"
  - "node_modules/**/*"
  - "tmp/**/*"
  - "log/**/*"
  - "storage/**/*"
  - "public/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
diagnostics:
  require_not_found: true
  require_paths: true
  typecheck: true
