require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/patients", type: :request do
  let(:professional) { create(:professional) }
  let(:user) { create(:user, account: professional) }
  let(:valid_attributes) do
    attributes_for(:patient)
  end
  let(:invalid_attributes) do
    { full_name: "x", email: "invalid", cpf: "123", birthday: nil }
  end

  before { sign_in user }

  describe "GET /index" do
    it "does not list soft-deleted records" do
      kept = Patient.create! valid_attributes
      deleted = Patient.create! valid_attributes.merge(cpf: '88888888888', email: 'deleted@hope.local')
      deleted.destroy
      get patients_url
      expect(response).to be_successful
      expect(response.body).to include(kept.full_name)
      expect(response.body).not_to include(deleted.full_name)
    end
  end

  describe "GET /show" do
    it "returns 404 for soft-deleted record" do
      patient = Patient.create! valid_attributes
      patient.destroy
      expect { get patient_url(patient) }.to raise_error(ActiveRecord::RecordNotFound)
    end
  end

  describe "PATCH /restore" do
    it "restores a soft-deleted patient" do
      patient = Patient.create! valid_attributes
      patient.destroy
      expect(Patient.only_deleted.find(patient.id)).to be_present

      patch restore_patient_url(patient)
      expect(response).to redirect_to(patient_url(patient))
      expect(Patient.find(patient.id)).to be_present
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_patient_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      patient = Patient.create! valid_attributes
      get edit_patient_url(patient)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Patient" do
        expect {
          post patients_url, params: { patient: valid_attributes }
        }.to change(Patient, :count).by(1)
      end

      it "redirects to the created patient" do
        post patients_url, params: { patient: valid_attributes }
        expect(response).to redirect_to(patient_url(Patient.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Patient" do
        expect {
          post patients_url, params: { patient: invalid_attributes }
        }.to change(Patient, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post patients_url, params: { patient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested patient" do
        patient = Patient.create! valid_attributes
        patch patient_url(patient), params: { patient: new_attributes }
        patient.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the patient" do
        patient = Patient.create! valid_attributes
        patch patient_url(patient), params: { patient: new_attributes }
        patient.reload
        expect(response).to redirect_to(patient_url(patient))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patient = Patient.create! valid_attributes
        patch patient_url(patient), params: { patient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "soft-deletes the requested patient" do
      patient = Patient.create! valid_attributes
      expect {
        delete patient_url(patient)
      }.to change(Patient, :count).by(-1)
      expect(Patient.only_deleted.find(patient.id)).to be_present
    end

    it "redirects to the patients list" do
      patient = Patient.create! valid_attributes
      delete patient_url(patient)
      expect(response).to redirect_to(patients_url)
    end
  end
end
