require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/professionals", type: :request do
  let(:professional) { create(:professional) }
  let(:user) { create(:user, account: professional) }
  let(:valid_attributes) do
    attributes_for(:professional)
  end
  let(:invalid_attributes) do
    { full_name: "x", email: "invalid", cpf: "123", birthday: nil }
  end

  before { sign_in user }

  describe "GET /index" do
    it "does not list soft-deleted records" do
      kept = Professional.create! valid_attributes
      deleted = Professional.create! valid_attributes.merge(cpf: '99999999999', email: 'deleted-pro@hope.local')
      deleted.destroy
      get professionals_url
      expect(response).to be_successful
      expect(response.body).to include(kept.full_name)
      expect(response.body).not_to include(deleted.full_name)
    end
  end

  describe "GET /show" do
    it "returns 404 for soft-deleted record" do
      professional = Professional.create! valid_attributes
      professional.destroy
      expect { get professional_url(professional) }.to raise_error(ActiveRecord::RecordNotFound)
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_professional_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      professional = Professional.create! valid_attributes
      get edit_professional_url(professional)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Professional" do
        expect {
          post professionals_url, params: { professional: valid_attributes }
        }.to change(Professional, :count).by(1)
      end

      it "redirects to the created professional" do
        post professionals_url, params: { professional: valid_attributes }
        expect(response).to redirect_to(professional_url(Professional.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Professional" do
        expect {
          post professionals_url, params: { professional: invalid_attributes }
        }.to change(Professional, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post professionals_url, params: { professional: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested professional" do
        professional = Professional.create! valid_attributes
        patch professional_url(professional), params: { professional: new_attributes }
        professional.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the professional" do
        professional = Professional.create! valid_attributes
        patch professional_url(professional), params: { professional: new_attributes }
        professional.reload
        expect(response).to redirect_to(professional_url(professional))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        professional = Professional.create! valid_attributes
        patch professional_url(professional), params: { professional: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "soft-deletes the requested professional" do
      professional = Professional.create! valid_attributes
      expect {
        delete professional_url(professional)
      }.to change(Professional, :count).by(-1)
      expect(Professional.only_deleted.find(professional.id)).to be_present
    end

    it "redirects to the professionals list" do
      professional = Professional.create! valid_attributes
      delete professional_url(professional)
      expect(response).to redirect_to(professionals_url)
    end
  end

  describe "PATCH /restore" do
    it "restores a soft-deleted professional" do
      professional = Professional.create! valid_attributes
      professional.destroy
      expect(Professional.only_deleted.find(professional.id)).to be_present

      patch restore_professional_url(professional)
      expect(response).to redirect_to(professional_url(professional))
      expect(Professional.find(professional.id)).to be_present
    end
  end
end
